import { defineConfig, loadEnv, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

/** Same-origin path the browser calls; the backend host sits behind it. */
const API_PATH = "/powerhub/v1/api";

/**
 * Netlify serves the build as static files, so the dev-server proxy below does
 * not apply there — `_redirects` does the proxying instead. It cannot read env
 * vars at runtime, so emit it at build time from the same target the dev proxy
 * uses and keep both environments on one source of truth.
 */
function netlifyRedirects(apiProxyTarget: string): Plugin {
  return {
    name: "emit-netlify-redirects",
    apply: "build",
    generateBundle() {
      this.emitFile({
        type: "asset",
        fileName: "_redirects",
        source: [
          "# Generated by vite.config.ts from API_PROXY_TARGET — do not edit by hand.",
          "",
          "# Keep API requests same-origin so cookie-based sessions and CSRF protection work.",
          `${API_PATH}/*  ${apiProxyTarget}${API_PATH}/:splat  200`,
          "",
          "# SPA fallback: serve index.html for every route so TanStack Router handles it",
          "/*    /index.html   200",
          "",
        ].join("\n"),
      });
    },
  };
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  // Empty prefix so unprefixed vars — including Netlify's build environment —
  // are visible here. Only VITE_-prefixed ones reach the client bundle.
  const env = loadEnv(mode, ".", "");
  const apiProxyTarget = env.API_PROXY_TARGET?.trim().replace(/\/$/, "");

  if (!apiProxyTarget) {
    throw new Error(
      "API_PROXY_TARGET is not set. Point it at the backend for this " +
        "environment (locally in .env, on Netlify as a build environment " +
        "variable scoped per deploy context).",
    );
  }

  const proxy = {
    [API_PATH]: {
      target: apiProxyTarget,
      changeOrigin: true,
    },
  };

  return {
    plugins: [
      tanstackRouter({
        target: "react",
        autoCodeSplitting: true,
      }),
      react(),
      netlifyRedirects(apiProxyTarget),
    ],
    server: { proxy },
    preview: { proxy },
  };
});
