/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationSetupRouteImport } from './routes/invitation-setup'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AppMeterRouteImport } from './routes/_app/meter'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AdminAdminRequestLogsRouteImport } from './routes/admin/_admin/request-logs'
import { Route as AdminAdminOrganizationManagementRouteImport } from './routes/admin/_admin/organization-management'
import { Route as AdminAdminIncidentReportRouteImport } from './routes/admin/_admin/incident-report'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin/_admin/dashboard'
import { Route as AdminAdminAuditLogsRouteImport } from './routes/admin/_admin/audit-logs'
import { Route as AppSettingsUserManagementRouteImport } from './routes/_app/settings/user-management'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings/api-keys'
import { Route as AdminAdminMeterIntegrationIndexRouteImport } from './routes/admin/_admin/meter-integration/index'
import { Route as AdminAdminApiManagementIndexRouteImport } from './routes/admin/_admin/api-management/index'
import { Route as AdminAdminSettingsUserManagementRouteImport } from './routes/admin/_admin/settings/user-management'
import { Route as AdminAdminSettingsProfileRouteImport } from './routes/admin/_admin/settings/profile'
import { Route as AdminAdminMeterIntegrationMeterIdRouteImport } from './routes/admin/_admin/meter-integration/$meterId'
import { Route as AdminAdminApiManagementApiIdRouteImport } from './routes/admin/_admin/api-management/$apiId'
import { Route as AdminAdminSettingsPlansIndexRouteImport } from './routes/admin/_admin/settings/plans/index'
import { Route as AdminAdminSettingsPlansPlanIdRouteImport } from './routes/admin/_admin/settings/plans/$planId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationSetupRoute = InvitationSetupRouteImport.update({
  id: '/invitation-setup',
  path: '/invitation-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeterRoute = AppMeterRouteImport.update({
  id: '/meter',
  path: '/meter',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRequestLogsRoute = AdminAdminRequestLogsRouteImport.update({
  id: '/request-logs',
  path: '/request-logs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOrganizationManagementRoute =
  AdminAdminOrganizationManagementRouteImport.update({
    id: '/organization-management',
    path: '/organization-management',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminIncidentReportRoute =
  AdminAdminIncidentReportRouteImport.update({
    id: '/incident-report',
    path: '/incident-report',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AppSettingsUserManagementRoute =
  AppSettingsUserManagementRouteImport.update({
    id: '/settings/user-management',
    path: '/settings/user-management',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminMeterIntegrationIndexRoute =
  AdminAdminMeterIntegrationIndexRouteImport.update({
    id: '/meter-integration/',
    path: '/meter-integration/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminApiManagementIndexRoute =
  AdminAdminApiManagementIndexRouteImport.update({
    id: '/api-management/',
    path: '/api-management/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminSettingsUserManagementRoute =
  AdminAdminSettingsUserManagementRouteImport.update({
    id: '/settings/user-management',
    path: '/settings/user-management',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminSettingsProfileRoute =
  AdminAdminSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminMeterIntegrationMeterIdRoute =
  AdminAdminMeterIntegrationMeterIdRouteImport.update({
    id: '/meter-integration/$meterId',
    path: '/meter-integration/$meterId',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminApiManagementApiIdRoute =
  AdminAdminApiManagementApiIdRouteImport.update({
    id: '/api-management/$apiId',
    path: '/api-management/$apiId',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminSettingsPlansIndexRoute =
  AdminAdminSettingsPlansIndexRouteImport.update({
    id: '/settings/plans/',
    path: '/settings/plans/',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminSettingsPlansPlanIdRoute =
  AdminAdminSettingsPlansPlanIdRouteImport.update({
    id: '/settings/plans/$planId',
    path: '/settings/plans/$planId',
    getParentRoute: () => AdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation-setup': typeof InvitationSetupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/logs': typeof AppLogsRoute
  '/meter': typeof AppMeterRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/user-management': typeof AppSettingsUserManagementRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/incident-report': typeof AdminAdminIncidentReportRoute
  '/admin/organization-management': typeof AdminAdminOrganizationManagementRoute
  '/admin/request-logs': typeof AdminAdminRequestLogsRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/admin/api-management/$apiId': typeof AdminAdminApiManagementApiIdRoute
  '/admin/meter-integration/$meterId': typeof AdminAdminMeterIntegrationMeterIdRoute
  '/admin/settings/profile': typeof AdminAdminSettingsProfileRoute
  '/admin/settings/user-management': typeof AdminAdminSettingsUserManagementRoute
  '/admin/api-management/': typeof AdminAdminApiManagementIndexRoute
  '/admin/meter-integration/': typeof AdminAdminMeterIntegrationIndexRoute
  '/admin/settings/plans/$planId': typeof AdminAdminSettingsPlansPlanIdRoute
  '/admin/settings/plans/': typeof AdminAdminSettingsPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation-setup': typeof InvitationSetupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/logs': typeof AppLogsRoute
  '/meter': typeof AppMeterRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/user-management': typeof AppSettingsUserManagementRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/incident-report': typeof AdminAdminIncidentReportRoute
  '/admin/organization-management': typeof AdminAdminOrganizationManagementRoute
  '/admin/request-logs': typeof AdminAdminRequestLogsRoute
  '/settings': typeof AppSettingsIndexRoute
  '/admin/api-management/$apiId': typeof AdminAdminApiManagementApiIdRoute
  '/admin/meter-integration/$meterId': typeof AdminAdminMeterIntegrationMeterIdRoute
  '/admin/settings/profile': typeof AdminAdminSettingsProfileRoute
  '/admin/settings/user-management': typeof AdminAdminSettingsUserManagementRoute
  '/admin/api-management': typeof AdminAdminApiManagementIndexRoute
  '/admin/meter-integration': typeof AdminAdminMeterIntegrationIndexRoute
  '/admin/settings/plans/$planId': typeof AdminAdminSettingsPlansPlanIdRoute
  '/admin/settings/plans': typeof AdminAdminSettingsPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation-setup': typeof InvitationSetupRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/meter': typeof AppMeterRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/user-management': typeof AppSettingsUserManagementRoute
  '/admin/_admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/_admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/_admin/incident-report': typeof AdminAdminIncidentReportRoute
  '/admin/_admin/organization-management': typeof AdminAdminOrganizationManagementRoute
  '/admin/_admin/request-logs': typeof AdminAdminRequestLogsRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/admin/_admin/api-management/$apiId': typeof AdminAdminApiManagementApiIdRoute
  '/admin/_admin/meter-integration/$meterId': typeof AdminAdminMeterIntegrationMeterIdRoute
  '/admin/_admin/settings/profile': typeof AdminAdminSettingsProfileRoute
  '/admin/_admin/settings/user-management': typeof AdminAdminSettingsUserManagementRoute
  '/admin/_admin/api-management/': typeof AdminAdminApiManagementIndexRoute
  '/admin/_admin/meter-integration/': typeof AdminAdminMeterIntegrationIndexRoute
  '/admin/_admin/settings/plans/$planId': typeof AdminAdminSettingsPlansPlanIdRoute
  '/admin/_admin/settings/plans/': typeof AdminAdminSettingsPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/invitation-setup'
    | '/login'
    | '/signup'
    | '/billing'
    | '/dashboard'
    | '/logs'
    | '/meter'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/docs/$slug'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/user-management'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/incident-report'
    | '/admin/organization-management'
    | '/admin/request-logs'
    | '/settings/'
    | '/admin/api-management/$apiId'
    | '/admin/meter-integration/$meterId'
    | '/admin/settings/profile'
    | '/admin/settings/user-management'
    | '/admin/api-management/'
    | '/admin/meter-integration/'
    | '/admin/settings/plans/$planId'
    | '/admin/settings/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/invitation-setup'
    | '/login'
    | '/signup'
    | '/billing'
    | '/dashboard'
    | '/logs'
    | '/meter'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/docs/$slug'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/user-management'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/incident-report'
    | '/admin/organization-management'
    | '/admin/request-logs'
    | '/settings'
    | '/admin/api-management/$apiId'
    | '/admin/meter-integration/$meterId'
    | '/admin/settings/profile'
    | '/admin/settings/user-management'
    | '/admin/api-management'
    | '/admin/meter-integration'
    | '/admin/settings/plans/$planId'
    | '/admin/settings/plans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/invitation-setup'
    | '/login'
    | '/signup'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/logs'
    | '/_app/meter'
    | '/admin/_admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/docs/$slug'
    | '/_app/settings/api-keys'
    | '/_app/settings/profile'
    | '/_app/settings/user-management'
    | '/admin/_admin/audit-logs'
    | '/admin/_admin/dashboard'
    | '/admin/_admin/incident-report'
    | '/admin/_admin/organization-management'
    | '/admin/_admin/request-logs'
    | '/_app/settings/'
    | '/admin/_admin/api-management/$apiId'
    | '/admin/_admin/meter-integration/$meterId'
    | '/admin/_admin/settings/profile'
    | '/admin/_admin/settings/user-management'
    | '/admin/_admin/api-management/'
    | '/admin/_admin/meter-integration/'
    | '/admin/_admin/settings/plans/$planId'
    | '/admin/_admin/settings/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvitationSetupRoute: typeof InvitationSetupRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DocsSlugRoute: typeof DocsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation-setup': {
      id: '/invitation-setup'
      path: '/invitation-setup'
      fullPath: '/invitation-setup'
      preLoaderRoute: typeof InvitationSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/meter': {
      id: '/_app/meter'
      path: '/meter'
      fullPath: '/meter'
      preLoaderRoute: typeof AppMeterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/_admin/request-logs': {
      id: '/admin/_admin/request-logs'
      path: '/request-logs'
      fullPath: '/admin/request-logs'
      preLoaderRoute: typeof AdminAdminRequestLogsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/organization-management': {
      id: '/admin/_admin/organization-management'
      path: '/organization-management'
      fullPath: '/admin/organization-management'
      preLoaderRoute: typeof AdminAdminOrganizationManagementRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/incident-report': {
      id: '/admin/_admin/incident-report'
      path: '/incident-report'
      fullPath: '/admin/incident-report'
      preLoaderRoute: typeof AdminAdminIncidentReportRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/dashboard': {
      id: '/admin/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/audit-logs': {
      id: '/admin/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAdminAuditLogsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_app/settings/user-management': {
      id: '/_app/settings/user-management'
      path: '/settings/user-management'
      fullPath: '/settings/user-management'
      preLoaderRoute: typeof AppSettingsUserManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/_admin/meter-integration/': {
      id: '/admin/_admin/meter-integration/'
      path: '/meter-integration'
      fullPath: '/admin/meter-integration/'
      preLoaderRoute: typeof AdminAdminMeterIntegrationIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/api-management/': {
      id: '/admin/_admin/api-management/'
      path: '/api-management'
      fullPath: '/admin/api-management/'
      preLoaderRoute: typeof AdminAdminApiManagementIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/settings/user-management': {
      id: '/admin/_admin/settings/user-management'
      path: '/settings/user-management'
      fullPath: '/admin/settings/user-management'
      preLoaderRoute: typeof AdminAdminSettingsUserManagementRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/settings/profile': {
      id: '/admin/_admin/settings/profile'
      path: '/settings/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminAdminSettingsProfileRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/meter-integration/$meterId': {
      id: '/admin/_admin/meter-integration/$meterId'
      path: '/meter-integration/$meterId'
      fullPath: '/admin/meter-integration/$meterId'
      preLoaderRoute: typeof AdminAdminMeterIntegrationMeterIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/api-management/$apiId': {
      id: '/admin/_admin/api-management/$apiId'
      path: '/api-management/$apiId'
      fullPath: '/admin/api-management/$apiId'
      preLoaderRoute: typeof AdminAdminApiManagementApiIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/settings/plans/': {
      id: '/admin/_admin/settings/plans/'
      path: '/settings/plans'
      fullPath: '/admin/settings/plans/'
      preLoaderRoute: typeof AdminAdminSettingsPlansIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/settings/plans/$planId': {
      id: '/admin/_admin/settings/plans/$planId'
      path: '/settings/plans/$planId'
      fullPath: '/admin/settings/plans/$planId'
      preLoaderRoute: typeof AdminAdminSettingsPlansPlanIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMeterRoute: typeof AppMeterRoute
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsUserManagementRoute: typeof AppSettingsUserManagementRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLogsRoute: AppLogsRoute,
  AppMeterRoute: AppMeterRoute,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsUserManagementRoute: AppSettingsUserManagementRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminAuditLogsRoute: typeof AdminAdminAuditLogsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminIncidentReportRoute: typeof AdminAdminIncidentReportRoute
  AdminAdminOrganizationManagementRoute: typeof AdminAdminOrganizationManagementRoute
  AdminAdminRequestLogsRoute: typeof AdminAdminRequestLogsRoute
  AdminAdminApiManagementApiIdRoute: typeof AdminAdminApiManagementApiIdRoute
  AdminAdminMeterIntegrationMeterIdRoute: typeof AdminAdminMeterIntegrationMeterIdRoute
  AdminAdminSettingsProfileRoute: typeof AdminAdminSettingsProfileRoute
  AdminAdminSettingsUserManagementRoute: typeof AdminAdminSettingsUserManagementRoute
  AdminAdminApiManagementIndexRoute: typeof AdminAdminApiManagementIndexRoute
  AdminAdminMeterIntegrationIndexRoute: typeof AdminAdminMeterIntegrationIndexRoute
  AdminAdminSettingsPlansPlanIdRoute: typeof AdminAdminSettingsPlansPlanIdRoute
  AdminAdminSettingsPlansIndexRoute: typeof AdminAdminSettingsPlansIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminIncidentReportRoute: AdminAdminIncidentReportRoute,
  AdminAdminOrganizationManagementRoute: AdminAdminOrganizationManagementRoute,
  AdminAdminRequestLogsRoute: AdminAdminRequestLogsRoute,
  AdminAdminApiManagementApiIdRoute: AdminAdminApiManagementApiIdRoute,
  AdminAdminMeterIntegrationMeterIdRoute:
    AdminAdminMeterIntegrationMeterIdRoute,
  AdminAdminSettingsProfileRoute: AdminAdminSettingsProfileRoute,
  AdminAdminSettingsUserManagementRoute: AdminAdminSettingsUserManagementRoute,
  AdminAdminApiManagementIndexRoute: AdminAdminApiManagementIndexRoute,
  AdminAdminMeterIntegrationIndexRoute: AdminAdminMeterIntegrationIndexRoute,
  AdminAdminSettingsPlansPlanIdRoute: AdminAdminSettingsPlansPlanIdRoute,
  AdminAdminSettingsPlansIndexRoute: AdminAdminSettingsPlansIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvitationSetupRoute: InvitationSetupRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  DocsSlugRoute: DocsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
